//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DataAccessService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataAccessService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDeals", ReplyAction="http://tempuri.org/IDataService/GetDealsResponse")]
        Entities.DbModels.Deal[] GetDeals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDeals", ReplyAction="http://tempuri.org/IDataService/GetDealsResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.Deal[]> GetDealsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUsers", ReplyAction="http://tempuri.org/IDataService/GetUsersResponse")]
        Entities.DbModels.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUsers", ReplyAction="http://tempuri.org/IDataService/GetUsersResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.User[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjectOfTransactions", ReplyAction="http://tempuri.org/IDataService/GetObjectOfTransactionsResponse")]
        Entities.DbModels.ObjectOfTransaction[] GetObjectOfTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjectOfTransactions", ReplyAction="http://tempuri.org/IDataService/GetObjectOfTransactionsResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.ObjectOfTransaction[]> GetObjectOfTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDealById", ReplyAction="http://tempuri.org/IDataService/GetDealByIdResponse")]
        Entities.DbModels.Deal GetDealById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDealById", ReplyAction="http://tempuri.org/IDataService/GetDealByIdResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.Deal> GetDealByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUserById", ReplyAction="http://tempuri.org/IDataService/GetUserByIdResponse")]
        Entities.DbModels.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUserById", ReplyAction="http://tempuri.org/IDataService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.User> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjectOfTransactionById", ReplyAction="http://tempuri.org/IDataService/GetObjectOfTransactionByIdResponse")]
        Entities.DbModels.ObjectOfTransaction GetObjectOfTransactionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjectOfTransactionById", ReplyAction="http://tempuri.org/IDataService/GetObjectOfTransactionByIdResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.ObjectOfTransaction> GetObjectOfTransactionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddDeal", ReplyAction="http://tempuri.org/IDataService/AddDealResponse")]
        void AddDeal(Entities.DbModels.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddDeal", ReplyAction="http://tempuri.org/IDataService/AddDealResponse")]
        System.Threading.Tasks.Task AddDealAsync(Entities.DbModels.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddUser", ReplyAction="http://tempuri.org/IDataService/AddUserResponse")]
        void AddUser(Entities.DbModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddUser", ReplyAction="http://tempuri.org/IDataService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(Entities.DbModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/AddObjectOfTransactionResponse")]
        void AddObjectOfTransaction(Entities.DbModels.ObjectOfTransaction objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/AddObjectOfTransactionResponse")]
        System.Threading.Tasks.Task AddObjectOfTransactionAsync(Entities.DbModels.ObjectOfTransaction objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteDeal", ReplyAction="http://tempuri.org/IDataService/DeleteDealResponse")]
        void DeleteDeal(Entities.DbModels.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteDeal", ReplyAction="http://tempuri.org/IDataService/DeleteDealResponse")]
        System.Threading.Tasks.Task DeleteDealAsync(Entities.DbModels.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteUser", ReplyAction="http://tempuri.org/IDataService/DeleteUserResponse")]
        void DeleteUser(Entities.DbModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteUser", ReplyAction="http://tempuri.org/IDataService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(Entities.DbModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/DeleteObjectOfTransactionResponse")]
        void DeleteObjectOfTransaction(Entities.DbModels.ObjectOfTransaction objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/DeleteObjectOfTransactionResponse")]
        System.Threading.Tasks.Task DeleteObjectOfTransactionAsync(Entities.DbModels.ObjectOfTransaction objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateDeal", ReplyAction="http://tempuri.org/IDataService/UpdateDealResponse")]
        void UpdateDeal(Entities.DbModels.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateDeal", ReplyAction="http://tempuri.org/IDataService/UpdateDealResponse")]
        System.Threading.Tasks.Task UpdateDealAsync(Entities.DbModels.Deal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateUser", ReplyAction="http://tempuri.org/IDataService/UpdateUserResponse")]
        void UpdateUser(Entities.DbModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateUser", ReplyAction="http://tempuri.org/IDataService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(Entities.DbModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/UpdateObjectOfTransactionResponse")]
        void UpdateObjectOfTransaction(Entities.DbModels.ObjectOfTransaction objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/UpdateObjectOfTransactionResponse")]
        System.Threading.Tasks.Task UpdateObjectOfTransactionAsync(Entities.DbModels.ObjectOfTransaction objectOfTransaction);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : Server.DataAccessService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Server.DataAccessService.IDataService>, Server.DataAccessService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.DbModels.Deal[] GetDeals() {
            return base.Channel.GetDeals();
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.Deal[]> GetDealsAsync() {
            return base.Channel.GetDealsAsync();
        }
        
        public Entities.DbModels.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.User[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public Entities.DbModels.ObjectOfTransaction[] GetObjectOfTransactions() {
            return base.Channel.GetObjectOfTransactions();
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.ObjectOfTransaction[]> GetObjectOfTransactionsAsync() {
            return base.Channel.GetObjectOfTransactionsAsync();
        }
        
        public Entities.DbModels.Deal GetDealById(int id) {
            return base.Channel.GetDealById(id);
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.Deal> GetDealByIdAsync(int id) {
            return base.Channel.GetDealByIdAsync(id);
        }
        
        public Entities.DbModels.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.User> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public Entities.DbModels.ObjectOfTransaction GetObjectOfTransactionById(int id) {
            return base.Channel.GetObjectOfTransactionById(id);
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.ObjectOfTransaction> GetObjectOfTransactionByIdAsync(int id) {
            return base.Channel.GetObjectOfTransactionByIdAsync(id);
        }
        
        public void AddDeal(Entities.DbModels.Deal deal) {
            base.Channel.AddDeal(deal);
        }
        
        public System.Threading.Tasks.Task AddDealAsync(Entities.DbModels.Deal deal) {
            return base.Channel.AddDealAsync(deal);
        }
        
        public void AddUser(Entities.DbModels.User user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(Entities.DbModels.User user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public void AddObjectOfTransaction(Entities.DbModels.ObjectOfTransaction objectOfTransaction) {
            base.Channel.AddObjectOfTransaction(objectOfTransaction);
        }
        
        public System.Threading.Tasks.Task AddObjectOfTransactionAsync(Entities.DbModels.ObjectOfTransaction objectOfTransaction) {
            return base.Channel.AddObjectOfTransactionAsync(objectOfTransaction);
        }
        
        public void DeleteDeal(Entities.DbModels.Deal deal) {
            base.Channel.DeleteDeal(deal);
        }
        
        public System.Threading.Tasks.Task DeleteDealAsync(Entities.DbModels.Deal deal) {
            return base.Channel.DeleteDealAsync(deal);
        }
        
        public void DeleteUser(Entities.DbModels.User user) {
            base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(Entities.DbModels.User user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public void DeleteObjectOfTransaction(Entities.DbModels.ObjectOfTransaction objectOfTransaction) {
            base.Channel.DeleteObjectOfTransaction(objectOfTransaction);
        }
        
        public System.Threading.Tasks.Task DeleteObjectOfTransactionAsync(Entities.DbModels.ObjectOfTransaction objectOfTransaction) {
            return base.Channel.DeleteObjectOfTransactionAsync(objectOfTransaction);
        }
        
        public void UpdateDeal(Entities.DbModels.Deal deal) {
            base.Channel.UpdateDeal(deal);
        }
        
        public System.Threading.Tasks.Task UpdateDealAsync(Entities.DbModels.Deal deal) {
            return base.Channel.UpdateDealAsync(deal);
        }
        
        public void UpdateUser(Entities.DbModels.User user) {
            base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(Entities.DbModels.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public void UpdateObjectOfTransaction(Entities.DbModels.ObjectOfTransaction objectOfTransaction) {
            base.Channel.UpdateObjectOfTransaction(objectOfTransaction);
        }
        
        public System.Threading.Tasks.Task UpdateObjectOfTransactionAsync(Entities.DbModels.ObjectOfTransaction objectOfTransaction) {
            return base.Channel.UpdateObjectOfTransactionAsync(objectOfTransaction);
        }
    }
}
