//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DataAccessService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChartRequestObject", Namespace="http://schemas.datacontract.org/2004/07/Entities.ChartModels")]
    [System.SerializableAttribute()]
    public partial class ChartRequestObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int objTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime toField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime from {
            get {
                return this.fromField;
            }
            set {
                if ((this.fromField.Equals(value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int objType {
            get {
                return this.objTypeField;
            }
            set {
                if ((this.objTypeField.Equals(value) != true)) {
                    this.objTypeField = value;
                    this.RaisePropertyChanged("objType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime to {
            get {
                return this.toField;
            }
            set {
                if ((this.toField.Equals(value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChartData", Namespace="http://schemas.datacontract.org/2004/07/Entities.ChartModels")]
    [System.SerializableAttribute()]
    public partial class ChartData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ApartmentProfitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CommercialPropertyProfitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HomesteadProfitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HouseProfitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ApartmentProfit {
            get {
                return this.ApartmentProfitField;
            }
            set {
                if ((this.ApartmentProfitField.Equals(value) != true)) {
                    this.ApartmentProfitField = value;
                    this.RaisePropertyChanged("ApartmentProfit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CommercialPropertyProfit {
            get {
                return this.CommercialPropertyProfitField;
            }
            set {
                if ((this.CommercialPropertyProfitField.Equals(value) != true)) {
                    this.CommercialPropertyProfitField = value;
                    this.RaisePropertyChanged("CommercialPropertyProfit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HomesteadProfit {
            get {
                return this.HomesteadProfitField;
            }
            set {
                if ((this.HomesteadProfitField.Equals(value) != true)) {
                    this.HomesteadProfitField = value;
                    this.RaisePropertyChanged("HomesteadProfit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HouseProfit {
            get {
                return this.HouseProfitField;
            }
            set {
                if ((this.HouseProfitField.Equals(value) != true)) {
                    this.HouseProfitField = value;
                    this.RaisePropertyChanged("HouseProfit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataAccessService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDeals", ReplyAction="http://tempuri.org/IDataService/GetDealsResponse")]
        Entities.ViewModels.ViewDeal[] GetDeals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDeals", ReplyAction="http://tempuri.org/IDataService/GetDealsResponse")]
        System.Threading.Tasks.Task<Entities.ViewModels.ViewDeal[]> GetDealsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUsers", ReplyAction="http://tempuri.org/IDataService/GetUsersResponse")]
        Entities.ViewModels.ViewUser[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUsers", ReplyAction="http://tempuri.org/IDataService/GetUsersResponse")]
        System.Threading.Tasks.Task<Entities.ViewModels.ViewUser[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjectOfTransactions", ReplyAction="http://tempuri.org/IDataService/GetObjectOfTransactionsResponse")]
        Entities.ViewModels.ViewObjOfTransact[] GetObjectOfTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjectOfTransactions", ReplyAction="http://tempuri.org/IDataService/GetObjectOfTransactionsResponse")]
        System.Threading.Tasks.Task<Entities.ViewModels.ViewObjOfTransact[]> GetObjectOfTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDealById", ReplyAction="http://tempuri.org/IDataService/GetDealByIdResponse")]
        Entities.DbModels.Deal GetDealById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDealById", ReplyAction="http://tempuri.org/IDataService/GetDealByIdResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.Deal> GetDealByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUserById", ReplyAction="http://tempuri.org/IDataService/GetUserByIdResponse")]
        Entities.DbModels.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUserById", ReplyAction="http://tempuri.org/IDataService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.User> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjectOfTransactionById", ReplyAction="http://tempuri.org/IDataService/GetObjectOfTransactionByIdResponse")]
        Entities.DbModels.ObjectOfTransaction GetObjectOfTransactionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjectOfTransactionById", ReplyAction="http://tempuri.org/IDataService/GetObjectOfTransactionByIdResponse")]
        System.Threading.Tasks.Task<Entities.DbModels.ObjectOfTransaction> GetObjectOfTransactionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddDeal", ReplyAction="http://tempuri.org/IDataService/AddDealResponse")]
        void AddDeal(Entities.ViewModels.ViewDeal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddDeal", ReplyAction="http://tempuri.org/IDataService/AddDealResponse")]
        System.Threading.Tasks.Task AddDealAsync(Entities.ViewModels.ViewDeal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddUser", ReplyAction="http://tempuri.org/IDataService/AddUserResponse")]
        void AddUser(Entities.ViewModels.ViewUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddUser", ReplyAction="http://tempuri.org/IDataService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(Entities.ViewModels.ViewUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/AddObjectOfTransactionResponse")]
        void AddObjectOfTransaction(Entities.ViewModels.ViewObjOfTransact objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/AddObjectOfTransactionResponse")]
        System.Threading.Tasks.Task AddObjectOfTransactionAsync(Entities.ViewModels.ViewObjOfTransact objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteDeal", ReplyAction="http://tempuri.org/IDataService/DeleteDealResponse")]
        void DeleteDeal(Entities.ViewModels.ViewDeal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteDeal", ReplyAction="http://tempuri.org/IDataService/DeleteDealResponse")]
        System.Threading.Tasks.Task DeleteDealAsync(Entities.ViewModels.ViewDeal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteUser", ReplyAction="http://tempuri.org/IDataService/DeleteUserResponse")]
        void DeleteUser(Entities.ViewModels.ViewUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteUser", ReplyAction="http://tempuri.org/IDataService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(Entities.ViewModels.ViewUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/DeleteObjectOfTransactionResponse")]
        void DeleteObjectOfTransaction(Entities.ViewModels.ViewObjOfTransact objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/DeleteObjectOfTransactionResponse")]
        System.Threading.Tasks.Task DeleteObjectOfTransactionAsync(Entities.ViewModels.ViewObjOfTransact objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateDeal", ReplyAction="http://tempuri.org/IDataService/UpdateDealResponse")]
        void UpdateDeal(Entities.ViewModels.ViewDeal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateDeal", ReplyAction="http://tempuri.org/IDataService/UpdateDealResponse")]
        System.Threading.Tasks.Task UpdateDealAsync(Entities.ViewModels.ViewDeal deal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateUser", ReplyAction="http://tempuri.org/IDataService/UpdateUserResponse")]
        void UpdateUser(Entities.ViewModels.ViewUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateUser", ReplyAction="http://tempuri.org/IDataService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(Entities.ViewModels.ViewUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/UpdateObjectOfTransactionResponse")]
        void UpdateObjectOfTransaction(Entities.ViewModels.ViewObjOfTransact objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateObjectOfTransaction", ReplyAction="http://tempuri.org/IDataService/UpdateObjectOfTransactionResponse")]
        System.Threading.Tasks.Task UpdateObjectOfTransactionAsync(Entities.ViewModels.ViewObjOfTransact objectOfTransaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUsersId", ReplyAction="http://tempuri.org/IDataService/GetUsersIdResponse")]
        int[] GetUsersId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUsersId", ReplyAction="http://tempuri.org/IDataService/GetUsersIdResponse")]
        System.Threading.Tasks.Task<int[]> GetUsersIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjOfTransactId", ReplyAction="http://tempuri.org/IDataService/GetObjOfTransactIdResponse")]
        int[] GetObjOfTransactId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetObjOfTransactId", ReplyAction="http://tempuri.org/IDataService/GetObjOfTransactIdResponse")]
        System.Threading.Tasks.Task<int[]> GetObjOfTransactIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSummaryOfProfits", ReplyAction="http://tempuri.org/IDataService/GetSummaryOfProfitsResponse")]
        Client.DataAccessService.ChartData GetSummaryOfProfits(Client.DataAccessService.ChartRequestObject chartLetter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSummaryOfProfits", ReplyAction="http://tempuri.org/IDataService/GetSummaryOfProfitsResponse")]
        System.Threading.Tasks.Task<Client.DataAccessService.ChartData> GetSummaryOfProfitsAsync(Client.DataAccessService.ChartRequestObject chartLetter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : Client.DataAccessService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Client.DataAccessService.IDataService>, Client.DataAccessService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.ViewModels.ViewDeal[] GetDeals() {
            return base.Channel.GetDeals();
        }
        
        public System.Threading.Tasks.Task<Entities.ViewModels.ViewDeal[]> GetDealsAsync() {
            return base.Channel.GetDealsAsync();
        }
        
        public Entities.ViewModels.ViewUser[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<Entities.ViewModels.ViewUser[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public Entities.ViewModels.ViewObjOfTransact[] GetObjectOfTransactions() {
            return base.Channel.GetObjectOfTransactions();
        }
        
        public System.Threading.Tasks.Task<Entities.ViewModels.ViewObjOfTransact[]> GetObjectOfTransactionsAsync() {
            return base.Channel.GetObjectOfTransactionsAsync();
        }
        
        public Entities.DbModels.Deal GetDealById(int id) {
            return base.Channel.GetDealById(id);
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.Deal> GetDealByIdAsync(int id) {
            return base.Channel.GetDealByIdAsync(id);
        }
        
        public Entities.DbModels.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.User> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public Entities.DbModels.ObjectOfTransaction GetObjectOfTransactionById(int id) {
            return base.Channel.GetObjectOfTransactionById(id);
        }
        
        public System.Threading.Tasks.Task<Entities.DbModels.ObjectOfTransaction> GetObjectOfTransactionByIdAsync(int id) {
            return base.Channel.GetObjectOfTransactionByIdAsync(id);
        }
        
        public void AddDeal(Entities.ViewModels.ViewDeal deal) {
            base.Channel.AddDeal(deal);
        }
        
        public System.Threading.Tasks.Task AddDealAsync(Entities.ViewModels.ViewDeal deal) {
            return base.Channel.AddDealAsync(deal);
        }
        
        public void AddUser(Entities.ViewModels.ViewUser user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(Entities.ViewModels.ViewUser user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public void AddObjectOfTransaction(Entities.ViewModels.ViewObjOfTransact objectOfTransaction) {
            base.Channel.AddObjectOfTransaction(objectOfTransaction);
        }
        
        public System.Threading.Tasks.Task AddObjectOfTransactionAsync(Entities.ViewModels.ViewObjOfTransact objectOfTransaction) {
            return base.Channel.AddObjectOfTransactionAsync(objectOfTransaction);
        }
        
        public void DeleteDeal(Entities.ViewModels.ViewDeal deal) {
            base.Channel.DeleteDeal(deal);
        }
        
        public System.Threading.Tasks.Task DeleteDealAsync(Entities.ViewModels.ViewDeal deal) {
            return base.Channel.DeleteDealAsync(deal);
        }
        
        public void DeleteUser(Entities.ViewModels.ViewUser user) {
            base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(Entities.ViewModels.ViewUser user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public void DeleteObjectOfTransaction(Entities.ViewModels.ViewObjOfTransact objectOfTransaction) {
            base.Channel.DeleteObjectOfTransaction(objectOfTransaction);
        }
        
        public System.Threading.Tasks.Task DeleteObjectOfTransactionAsync(Entities.ViewModels.ViewObjOfTransact objectOfTransaction) {
            return base.Channel.DeleteObjectOfTransactionAsync(objectOfTransaction);
        }
        
        public void UpdateDeal(Entities.ViewModels.ViewDeal deal) {
            base.Channel.UpdateDeal(deal);
        }
        
        public System.Threading.Tasks.Task UpdateDealAsync(Entities.ViewModels.ViewDeal deal) {
            return base.Channel.UpdateDealAsync(deal);
        }
        
        public void UpdateUser(Entities.ViewModels.ViewUser user) {
            base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(Entities.ViewModels.ViewUser user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public void UpdateObjectOfTransaction(Entities.ViewModels.ViewObjOfTransact objectOfTransaction) {
            base.Channel.UpdateObjectOfTransaction(objectOfTransaction);
        }
        
        public System.Threading.Tasks.Task UpdateObjectOfTransactionAsync(Entities.ViewModels.ViewObjOfTransact objectOfTransaction) {
            return base.Channel.UpdateObjectOfTransactionAsync(objectOfTransaction);
        }
        
        public int[] GetUsersId() {
            return base.Channel.GetUsersId();
        }
        
        public System.Threading.Tasks.Task<int[]> GetUsersIdAsync() {
            return base.Channel.GetUsersIdAsync();
        }
        
        public int[] GetObjOfTransactId() {
            return base.Channel.GetObjOfTransactId();
        }
        
        public System.Threading.Tasks.Task<int[]> GetObjOfTransactIdAsync() {
            return base.Channel.GetObjOfTransactIdAsync();
        }
        
        public Client.DataAccessService.ChartData GetSummaryOfProfits(Client.DataAccessService.ChartRequestObject chartLetter) {
            return base.Channel.GetSummaryOfProfits(chartLetter);
        }
        
        public System.Threading.Tasks.Task<Client.DataAccessService.ChartData> GetSummaryOfProfitsAsync(Client.DataAccessService.ChartRequestObject chartLetter) {
            return base.Channel.GetSummaryOfProfitsAsync(chartLetter);
        }
    }
}
